twitter: "https://twitter.com/patricknugros"
github: "https://github.com/patricknugros"
instagram: "https://instagram.com/patricknugros"
youtube: "https://youtube.com"
facebook: "https://facebook.com/patricknugros"
medium: "https://medium.com/patricknugros"
patreon: ""
paypal: ""
unsplash: ""
