baseURL: "https://blog.patricknugros.com"
languageCode: "en-us"
title: "Patrick Nugros"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
